#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinqToSqlTest
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="FFSLJ")]
	public partial class testDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertBCS_District(BCS_District instance);
    partial void UpdateBCS_District(BCS_District instance);
    partial void DeleteBCS_District(BCS_District instance);
    partial void InsertBCS_MeterReadingRoute(BCS_MeterReadingRoute instance);
    partial void UpdateBCS_MeterReadingRoute(BCS_MeterReadingRoute instance);
    partial void DeleteBCS_MeterReadingRoute(BCS_MeterReadingRoute instance);
    partial void InsertBCS_Charge(BCS_Charge instance);
    partial void UpdateBCS_Charge(BCS_Charge instance);
    partial void DeleteBCS_Charge(BCS_Charge instance);
    #endregion
		
		public testDataContext() : 
				base(global::LinqToSqlTest.Properties.Settings.Default.FFSLJConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public testDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public testDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public testDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public testDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<BCS_District> BCS_District
		{
			get
			{
				return this.GetTable<BCS_District>();
			}
		}
		
		public System.Data.Linq.Table<BCS_MeterReadingRoute> BCS_MeterReadingRoute
		{
			get
			{
				return this.GetTable<BCS_MeterReadingRoute>();
			}
		}
		
		public System.Data.Linq.Table<BCS_Charge> BCS_Charge
		{
			get
			{
				return this.GetTable<BCS_Charge>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BCS_District")]
	public partial class BCS_District : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Dis_ID;
		
		private string _DepartmentCode;
		
		private string _Code;
		
		private string _DistrictName;
		
		private System.Nullable<int> _MeterReadingRouteID;
		
		private System.Data.Linq.Binary @__MASK_SYNC_V2;
		
		private string _MeterReader;
		
		private System.DateTime _CreateDT;
		
		private System.DateTime _ReviseDT;
		
		private string _Operator;
		
		private string _Creator;
		
		private string _OldCode;
		
		private System.Nullable<int> _AllowOnlinePay;
		
		private string _CollCollector;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDis_IDChanging(long value);
    partial void OnDis_IDChanged();
    partial void OnDepartmentCodeChanging(string value);
    partial void OnDepartmentCodeChanged();
    partial void OnCodeChanging(string value);
    partial void OnCodeChanged();
    partial void OnDistrictNameChanging(string value);
    partial void OnDistrictNameChanged();
    partial void OnMeterReadingRouteIDChanging(System.Nullable<int> value);
    partial void OnMeterReadingRouteIDChanged();
    partial void On_MASK_SYNC_V2Changing(System.Data.Linq.Binary value);
    partial void On_MASK_SYNC_V2Changed();
    partial void OnMeterReaderChanging(string value);
    partial void OnMeterReaderChanged();
    partial void OnCreateDTChanging(System.DateTime value);
    partial void OnCreateDTChanged();
    partial void OnReviseDTChanging(System.DateTime value);
    partial void OnReviseDTChanged();
    partial void OnOperatorChanging(string value);
    partial void OnOperatorChanged();
    partial void OnCreatorChanging(string value);
    partial void OnCreatorChanged();
    partial void OnOldCodeChanging(string value);
    partial void OnOldCodeChanged();
    partial void OnAllowOnlinePayChanging(System.Nullable<int> value);
    partial void OnAllowOnlinePayChanged();
    partial void OnCollCollectorChanging(string value);
    partial void OnCollCollectorChanged();
    #endregion
		
		public BCS_District()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dis_ID", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public long Dis_ID
		{
			get
			{
				return this._Dis_ID;
			}
			set
			{
				if ((this._Dis_ID != value))
				{
					this.OnDis_IDChanging(value);
					this.SendPropertyChanging();
					this._Dis_ID = value;
					this.SendPropertyChanged("Dis_ID");
					this.OnDis_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DepartmentCode", DbType="VarChar(50) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string DepartmentCode
		{
			get
			{
				return this._DepartmentCode;
			}
			set
			{
				if ((this._DepartmentCode != value))
				{
					this.OnDepartmentCodeChanging(value);
					this.SendPropertyChanging();
					this._DepartmentCode = value;
					this.SendPropertyChanged("DepartmentCode");
					this.OnDepartmentCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="VarChar(6) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this.OnCodeChanging(value);
					this.SendPropertyChanging();
					this._Code = value;
					this.SendPropertyChanged("Code");
					this.OnCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DistrictName", DbType="VarChar(40) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string DistrictName
		{
			get
			{
				return this._DistrictName;
			}
			set
			{
				if ((this._DistrictName != value))
				{
					this.OnDistrictNameChanging(value);
					this.SendPropertyChanging();
					this._DistrictName = value;
					this.SendPropertyChanged("DistrictName");
					this.OnDistrictNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MeterReadingRouteID", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> MeterReadingRouteID
		{
			get
			{
				return this._MeterReadingRouteID;
			}
			set
			{
				if ((this._MeterReadingRouteID != value))
				{
					this.OnMeterReadingRouteIDChanging(value);
					this.SendPropertyChanging();
					this._MeterReadingRouteID = value;
					this.SendPropertyChanged("MeterReadingRouteID");
					this.OnMeterReadingRouteIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_MASK_SYNC_V2]", Storage="__MASK_SYNC_V2", AutoSync=AutoSync.Always, DbType="rowversion", IsDbGenerated=true, IsVersion=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary _MASK_SYNC_V2
		{
			get
			{
				return this.@__MASK_SYNC_V2;
			}
			set
			{
				if ((this.@__MASK_SYNC_V2 != value))
				{
					this.On_MASK_SYNC_V2Changing(value);
					this.SendPropertyChanging();
					this.@__MASK_SYNC_V2 = value;
					this.SendPropertyChanged("_MASK_SYNC_V2");
					this.On_MASK_SYNC_V2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MeterReader", DbType="VarChar(16)", UpdateCheck=UpdateCheck.Never)]
		public string MeterReader
		{
			get
			{
				return this._MeterReader;
			}
			set
			{
				if ((this._MeterReader != value))
				{
					this.OnMeterReaderChanging(value);
					this.SendPropertyChanging();
					this._MeterReader = value;
					this.SendPropertyChanged("MeterReader");
					this.OnMeterReaderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDT", DbType="DateTime NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.DateTime CreateDT
		{
			get
			{
				return this._CreateDT;
			}
			set
			{
				if ((this._CreateDT != value))
				{
					this.OnCreateDTChanging(value);
					this.SendPropertyChanging();
					this._CreateDT = value;
					this.SendPropertyChanged("CreateDT");
					this.OnCreateDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReviseDT", DbType="DateTime NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.DateTime ReviseDT
		{
			get
			{
				return this._ReviseDT;
			}
			set
			{
				if ((this._ReviseDT != value))
				{
					this.OnReviseDTChanging(value);
					this.SendPropertyChanging();
					this._ReviseDT = value;
					this.SendPropertyChanged("ReviseDT");
					this.OnReviseDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Operator", DbType="VarChar(16) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Operator
		{
			get
			{
				return this._Operator;
			}
			set
			{
				if ((this._Operator != value))
				{
					this.OnOperatorChanging(value);
					this.SendPropertyChanging();
					this._Operator = value;
					this.SendPropertyChanged("Operator");
					this.OnOperatorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Creator", DbType="VarChar(16) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Creator
		{
			get
			{
				return this._Creator;
			}
			set
			{
				if ((this._Creator != value))
				{
					this.OnCreatorChanging(value);
					this.SendPropertyChanging();
					this._Creator = value;
					this.SendPropertyChanged("Creator");
					this.OnCreatorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OldCode", DbType="VarChar(10)", UpdateCheck=UpdateCheck.Never)]
		public string OldCode
		{
			get
			{
				return this._OldCode;
			}
			set
			{
				if ((this._OldCode != value))
				{
					this.OnOldCodeChanging(value);
					this.SendPropertyChanging();
					this._OldCode = value;
					this.SendPropertyChanged("OldCode");
					this.OnOldCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AllowOnlinePay", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> AllowOnlinePay
		{
			get
			{
				return this._AllowOnlinePay;
			}
			set
			{
				if ((this._AllowOnlinePay != value))
				{
					this.OnAllowOnlinePayChanging(value);
					this.SendPropertyChanging();
					this._AllowOnlinePay = value;
					this.SendPropertyChanged("AllowOnlinePay");
					this.OnAllowOnlinePayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CollCollector", DbType="NVarChar(200)", UpdateCheck=UpdateCheck.Never)]
		public string CollCollector
		{
			get
			{
				return this._CollCollector;
			}
			set
			{
				if ((this._CollCollector != value))
				{
					this.OnCollCollectorChanging(value);
					this.SendPropertyChanging();
					this._CollCollector = value;
					this.SendPropertyChanged("CollCollector");
					this.OnCollCollectorChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BCS_MeterReadingRoute")]
	public partial class BCS_MeterReadingRoute : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _MRR_ID;
		
		private string _DepartmentCode;
		
		private string _RouteName;
		
		private string _RouteCode;
		
		private System.DateTime _CreateDT;
		
		private System.DateTime _ReviseDT;
		
		private string _Creator;
		
		private string _Operator;
		
		private System.Nullable<int> _ReadingDate;
		
		private System.Nullable<int> _AllowDownloadStart;
		
		private System.Nullable<int> _AllowDownloadEnd;
		
		private string _OldCode;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMRR_IDChanging(long value);
    partial void OnMRR_IDChanged();
    partial void OnDepartmentCodeChanging(string value);
    partial void OnDepartmentCodeChanged();
    partial void OnRouteNameChanging(string value);
    partial void OnRouteNameChanged();
    partial void OnRouteCodeChanging(string value);
    partial void OnRouteCodeChanged();
    partial void OnCreateDTChanging(System.DateTime value);
    partial void OnCreateDTChanged();
    partial void OnReviseDTChanging(System.DateTime value);
    partial void OnReviseDTChanged();
    partial void OnCreatorChanging(string value);
    partial void OnCreatorChanged();
    partial void OnOperatorChanging(string value);
    partial void OnOperatorChanged();
    partial void OnReadingDateChanging(System.Nullable<int> value);
    partial void OnReadingDateChanged();
    partial void OnAllowDownloadStartChanging(System.Nullable<int> value);
    partial void OnAllowDownloadStartChanged();
    partial void OnAllowDownloadEndChanging(System.Nullable<int> value);
    partial void OnAllowDownloadEndChanged();
    partial void OnOldCodeChanging(string value);
    partial void OnOldCodeChanged();
    #endregion
		
		public BCS_MeterReadingRoute()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MRR_ID", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long MRR_ID
		{
			get
			{
				return this._MRR_ID;
			}
			set
			{
				if ((this._MRR_ID != value))
				{
					this.OnMRR_IDChanging(value);
					this.SendPropertyChanging();
					this._MRR_ID = value;
					this.SendPropertyChanged("MRR_ID");
					this.OnMRR_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DepartmentCode", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string DepartmentCode
		{
			get
			{
				return this._DepartmentCode;
			}
			set
			{
				if ((this._DepartmentCode != value))
				{
					this.OnDepartmentCodeChanging(value);
					this.SendPropertyChanging();
					this._DepartmentCode = value;
					this.SendPropertyChanged("DepartmentCode");
					this.OnDepartmentCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RouteName", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string RouteName
		{
			get
			{
				return this._RouteName;
			}
			set
			{
				if ((this._RouteName != value))
				{
					this.OnRouteNameChanging(value);
					this.SendPropertyChanging();
					this._RouteName = value;
					this.SendPropertyChanged("RouteName");
					this.OnRouteNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RouteCode", DbType="VarChar(6) NOT NULL", CanBeNull=false)]
		public string RouteCode
		{
			get
			{
				return this._RouteCode;
			}
			set
			{
				if ((this._RouteCode != value))
				{
					this.OnRouteCodeChanging(value);
					this.SendPropertyChanging();
					this._RouteCode = value;
					this.SendPropertyChanged("RouteCode");
					this.OnRouteCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDT", DbType="DateTime NOT NULL")]
		public System.DateTime CreateDT
		{
			get
			{
				return this._CreateDT;
			}
			set
			{
				if ((this._CreateDT != value))
				{
					this.OnCreateDTChanging(value);
					this.SendPropertyChanging();
					this._CreateDT = value;
					this.SendPropertyChanged("CreateDT");
					this.OnCreateDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReviseDT", DbType="DateTime NOT NULL")]
		public System.DateTime ReviseDT
		{
			get
			{
				return this._ReviseDT;
			}
			set
			{
				if ((this._ReviseDT != value))
				{
					this.OnReviseDTChanging(value);
					this.SendPropertyChanging();
					this._ReviseDT = value;
					this.SendPropertyChanged("ReviseDT");
					this.OnReviseDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Creator", DbType="VarChar(16) NOT NULL", CanBeNull=false)]
		public string Creator
		{
			get
			{
				return this._Creator;
			}
			set
			{
				if ((this._Creator != value))
				{
					this.OnCreatorChanging(value);
					this.SendPropertyChanging();
					this._Creator = value;
					this.SendPropertyChanged("Creator");
					this.OnCreatorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Operator", DbType="VarChar(16) NOT NULL", CanBeNull=false)]
		public string Operator
		{
			get
			{
				return this._Operator;
			}
			set
			{
				if ((this._Operator != value))
				{
					this.OnOperatorChanging(value);
					this.SendPropertyChanging();
					this._Operator = value;
					this.SendPropertyChanged("Operator");
					this.OnOperatorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReadingDate", DbType="Int")]
		public System.Nullable<int> ReadingDate
		{
			get
			{
				return this._ReadingDate;
			}
			set
			{
				if ((this._ReadingDate != value))
				{
					this.OnReadingDateChanging(value);
					this.SendPropertyChanging();
					this._ReadingDate = value;
					this.SendPropertyChanged("ReadingDate");
					this.OnReadingDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AllowDownloadStart", DbType="Int")]
		public System.Nullable<int> AllowDownloadStart
		{
			get
			{
				return this._AllowDownloadStart;
			}
			set
			{
				if ((this._AllowDownloadStart != value))
				{
					this.OnAllowDownloadStartChanging(value);
					this.SendPropertyChanging();
					this._AllowDownloadStart = value;
					this.SendPropertyChanged("AllowDownloadStart");
					this.OnAllowDownloadStartChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AllowDownloadEnd", DbType="Int")]
		public System.Nullable<int> AllowDownloadEnd
		{
			get
			{
				return this._AllowDownloadEnd;
			}
			set
			{
				if ((this._AllowDownloadEnd != value))
				{
					this.OnAllowDownloadEndChanging(value);
					this.SendPropertyChanging();
					this._AllowDownloadEnd = value;
					this.SendPropertyChanged("AllowDownloadEnd");
					this.OnAllowDownloadEndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OldCode", DbType="VarChar(10)")]
		public string OldCode
		{
			get
			{
				return this._OldCode;
			}
			set
			{
				if ((this._OldCode != value))
				{
					this.OnOldCodeChanging(value);
					this.SendPropertyChanging();
					this._OldCode = value;
					this.SendPropertyChanged("OldCode");
					this.OnOldCodeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BCS_Charge")]
	public partial class BCS_Charge : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Charge_ID;
		
		private string _InvoiceCode;
		
		private System.Nullable<long> _PriceMonth_ID;
		
		private System.Nullable<long> _BM_ID;
		
		private System.DateTime _GetMoneyTime;
		
		private string _DepartmentCode;
		
		private System.Nullable<long> _CM_ID;
		
		private decimal _UsedWaterNumber;
		
		private decimal _GetMoney;
		
		private string _BankOfDeposit;
		
		private System.Nullable<long> _GetMoneyPersonId;
		
		private string _GetMoneyPersonName;
		
		private short _state;
		
		private decimal _PlanMoney;
		
		private decimal _LastBalance;
		
		private decimal _ThisBalance;
		
		private bool _InvoiceOver;
		
		private bool _BookOver;
		
		private string _OldInvoiceCode;
		
		private System.Nullable<byte> _PosYn;
		
		private System.Nullable<decimal> _PosMoney;
		
		private System.Nullable<int> _CardType;
		
		private System.Nullable<byte> _AdvanceYn;
		
		private System.Nullable<int> _MoneyType;
		
		private string _BalanceDt;
		
		private byte _AdvanceReturn;
		
		private System.DateTime _CreateDT;
		
		private System.DateTime _ReviseDT;
		
		private string _Creator;
		
		private string _Operator;
		
		private string _Old定价;
		
		private string _Old年月;
		
		private string _Old客户;
		
		private string _Old水表;
		
		private string _Old支付方式;
		
		private string _OldUser;
		
		private string _otherOrderCode;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCharge_IDChanging(long value);
    partial void OnCharge_IDChanged();
    partial void OnInvoiceCodeChanging(string value);
    partial void OnInvoiceCodeChanged();
    partial void OnPriceMonth_IDChanging(System.Nullable<long> value);
    partial void OnPriceMonth_IDChanged();
    partial void OnBM_IDChanging(System.Nullable<long> value);
    partial void OnBM_IDChanged();
    partial void OnGetMoneyTimeChanging(System.DateTime value);
    partial void OnGetMoneyTimeChanged();
    partial void OnDepartmentCodeChanging(string value);
    partial void OnDepartmentCodeChanged();
    partial void OnCM_IDChanging(System.Nullable<long> value);
    partial void OnCM_IDChanged();
    partial void OnUsedWaterNumberChanging(decimal value);
    partial void OnUsedWaterNumberChanged();
    partial void OnGetMoneyChanging(decimal value);
    partial void OnGetMoneyChanged();
    partial void OnBankOfDepositChanging(string value);
    partial void OnBankOfDepositChanged();
    partial void OnGetMoneyPersonIdChanging(System.Nullable<long> value);
    partial void OnGetMoneyPersonIdChanged();
    partial void OnGetMoneyPersonNameChanging(string value);
    partial void OnGetMoneyPersonNameChanged();
    partial void OnstateChanging(short value);
    partial void OnstateChanged();
    partial void OnPlanMoneyChanging(decimal value);
    partial void OnPlanMoneyChanged();
    partial void OnLastBalanceChanging(decimal value);
    partial void OnLastBalanceChanged();
    partial void OnThisBalanceChanging(decimal value);
    partial void OnThisBalanceChanged();
    partial void OnInvoiceOverChanging(bool value);
    partial void OnInvoiceOverChanged();
    partial void OnBookOverChanging(bool value);
    partial void OnBookOverChanged();
    partial void OnOldInvoiceCodeChanging(string value);
    partial void OnOldInvoiceCodeChanged();
    partial void OnPosYnChanging(System.Nullable<byte> value);
    partial void OnPosYnChanged();
    partial void OnPosMoneyChanging(System.Nullable<decimal> value);
    partial void OnPosMoneyChanged();
    partial void OnCardTypeChanging(System.Nullable<int> value);
    partial void OnCardTypeChanged();
    partial void OnAdvanceYnChanging(System.Nullable<byte> value);
    partial void OnAdvanceYnChanged();
    partial void OnMoneyTypeChanging(System.Nullable<int> value);
    partial void OnMoneyTypeChanged();
    partial void OnBalanceDtChanging(string value);
    partial void OnBalanceDtChanged();
    partial void OnAdvanceReturnChanging(byte value);
    partial void OnAdvanceReturnChanged();
    partial void OnCreateDTChanging(System.DateTime value);
    partial void OnCreateDTChanged();
    partial void OnReviseDTChanging(System.DateTime value);
    partial void OnReviseDTChanged();
    partial void OnCreatorChanging(string value);
    partial void OnCreatorChanged();
    partial void OnOperatorChanging(string value);
    partial void OnOperatorChanged();
    partial void OnOld定价Changing(string value);
    partial void OnOld定价Changed();
    partial void OnOld年月Changing(string value);
    partial void OnOld年月Changed();
    partial void OnOld客户Changing(string value);
    partial void OnOld客户Changed();
    partial void OnOld水表Changing(string value);
    partial void OnOld水表Changed();
    partial void OnOld支付方式Changing(string value);
    partial void OnOld支付方式Changed();
    partial void OnOldUserChanging(string value);
    partial void OnOldUserChanged();
    partial void OnotherOrderCodeChanging(string value);
    partial void OnotherOrderCodeChanged();
    #endregion
		
		public BCS_Charge()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Charge_ID", AutoSync=AutoSync.Always, DbType="BigInt NOT NULL IDENTITY", IsDbGenerated=true)]
		public long Charge_ID
		{
			get
			{
				return this._Charge_ID;
			}
			set
			{
				if ((this._Charge_ID != value))
				{
					this.OnCharge_IDChanging(value);
					this.SendPropertyChanging();
					this._Charge_ID = value;
					this.SendPropertyChanged("Charge_ID");
					this.OnCharge_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceCode", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string InvoiceCode
		{
			get
			{
				return this._InvoiceCode;
			}
			set
			{
				if ((this._InvoiceCode != value))
				{
					this.OnInvoiceCodeChanging(value);
					this.SendPropertyChanging();
					this._InvoiceCode = value;
					this.SendPropertyChanged("InvoiceCode");
					this.OnInvoiceCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PriceMonth_ID", DbType="BigInt")]
		public System.Nullable<long> PriceMonth_ID
		{
			get
			{
				return this._PriceMonth_ID;
			}
			set
			{
				if ((this._PriceMonth_ID != value))
				{
					this.OnPriceMonth_IDChanging(value);
					this.SendPropertyChanging();
					this._PriceMonth_ID = value;
					this.SendPropertyChanged("PriceMonth_ID");
					this.OnPriceMonth_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BM_ID", DbType="BigInt")]
		public System.Nullable<long> BM_ID
		{
			get
			{
				return this._BM_ID;
			}
			set
			{
				if ((this._BM_ID != value))
				{
					this.OnBM_IDChanging(value);
					this.SendPropertyChanging();
					this._BM_ID = value;
					this.SendPropertyChanged("BM_ID");
					this.OnBM_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GetMoneyTime", DbType="DateTime NOT NULL")]
		public System.DateTime GetMoneyTime
		{
			get
			{
				return this._GetMoneyTime;
			}
			set
			{
				if ((this._GetMoneyTime != value))
				{
					this.OnGetMoneyTimeChanging(value);
					this.SendPropertyChanging();
					this._GetMoneyTime = value;
					this.SendPropertyChanged("GetMoneyTime");
					this.OnGetMoneyTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DepartmentCode", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string DepartmentCode
		{
			get
			{
				return this._DepartmentCode;
			}
			set
			{
				if ((this._DepartmentCode != value))
				{
					this.OnDepartmentCodeChanging(value);
					this.SendPropertyChanging();
					this._DepartmentCode = value;
					this.SendPropertyChanged("DepartmentCode");
					this.OnDepartmentCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CM_ID", DbType="BigInt")]
		public System.Nullable<long> CM_ID
		{
			get
			{
				return this._CM_ID;
			}
			set
			{
				if ((this._CM_ID != value))
				{
					this.OnCM_IDChanging(value);
					this.SendPropertyChanging();
					this._CM_ID = value;
					this.SendPropertyChanged("CM_ID");
					this.OnCM_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsedWaterNumber", DbType="Money NOT NULL")]
		public decimal UsedWaterNumber
		{
			get
			{
				return this._UsedWaterNumber;
			}
			set
			{
				if ((this._UsedWaterNumber != value))
				{
					this.OnUsedWaterNumberChanging(value);
					this.SendPropertyChanging();
					this._UsedWaterNumber = value;
					this.SendPropertyChanged("UsedWaterNumber");
					this.OnUsedWaterNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GetMoney", DbType="Money NOT NULL")]
		public decimal GetMoney
		{
			get
			{
				return this._GetMoney;
			}
			set
			{
				if ((this._GetMoney != value))
				{
					this.OnGetMoneyChanging(value);
					this.SendPropertyChanging();
					this._GetMoney = value;
					this.SendPropertyChanged("GetMoney");
					this.OnGetMoneyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BankOfDeposit", DbType="VarChar(2)")]
		public string BankOfDeposit
		{
			get
			{
				return this._BankOfDeposit;
			}
			set
			{
				if ((this._BankOfDeposit != value))
				{
					this.OnBankOfDepositChanging(value);
					this.SendPropertyChanging();
					this._BankOfDeposit = value;
					this.SendPropertyChanged("BankOfDeposit");
					this.OnBankOfDepositChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GetMoneyPersonId", DbType="BigInt")]
		public System.Nullable<long> GetMoneyPersonId
		{
			get
			{
				return this._GetMoneyPersonId;
			}
			set
			{
				if ((this._GetMoneyPersonId != value))
				{
					this.OnGetMoneyPersonIdChanging(value);
					this.SendPropertyChanging();
					this._GetMoneyPersonId = value;
					this.SendPropertyChanged("GetMoneyPersonId");
					this.OnGetMoneyPersonIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GetMoneyPersonName", DbType="VarChar(20)")]
		public string GetMoneyPersonName
		{
			get
			{
				return this._GetMoneyPersonName;
			}
			set
			{
				if ((this._GetMoneyPersonName != value))
				{
					this.OnGetMoneyPersonNameChanging(value);
					this.SendPropertyChanging();
					this._GetMoneyPersonName = value;
					this.SendPropertyChanged("GetMoneyPersonName");
					this.OnGetMoneyPersonNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_state", DbType="SmallInt NOT NULL")]
		public short state
		{
			get
			{
				return this._state;
			}
			set
			{
				if ((this._state != value))
				{
					this.OnstateChanging(value);
					this.SendPropertyChanging();
					this._state = value;
					this.SendPropertyChanged("state");
					this.OnstateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PlanMoney", DbType="Money NOT NULL")]
		public decimal PlanMoney
		{
			get
			{
				return this._PlanMoney;
			}
			set
			{
				if ((this._PlanMoney != value))
				{
					this.OnPlanMoneyChanging(value);
					this.SendPropertyChanging();
					this._PlanMoney = value;
					this.SendPropertyChanged("PlanMoney");
					this.OnPlanMoneyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastBalance", DbType="Money NOT NULL")]
		public decimal LastBalance
		{
			get
			{
				return this._LastBalance;
			}
			set
			{
				if ((this._LastBalance != value))
				{
					this.OnLastBalanceChanging(value);
					this.SendPropertyChanging();
					this._LastBalance = value;
					this.SendPropertyChanged("LastBalance");
					this.OnLastBalanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThisBalance", DbType="Money NOT NULL")]
		public decimal ThisBalance
		{
			get
			{
				return this._ThisBalance;
			}
			set
			{
				if ((this._ThisBalance != value))
				{
					this.OnThisBalanceChanging(value);
					this.SendPropertyChanging();
					this._ThisBalance = value;
					this.SendPropertyChanged("ThisBalance");
					this.OnThisBalanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceOver", DbType="Bit NOT NULL")]
		public bool InvoiceOver
		{
			get
			{
				return this._InvoiceOver;
			}
			set
			{
				if ((this._InvoiceOver != value))
				{
					this.OnInvoiceOverChanging(value);
					this.SendPropertyChanging();
					this._InvoiceOver = value;
					this.SendPropertyChanged("InvoiceOver");
					this.OnInvoiceOverChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BookOver", DbType="Bit NOT NULL")]
		public bool BookOver
		{
			get
			{
				return this._BookOver;
			}
			set
			{
				if ((this._BookOver != value))
				{
					this.OnBookOverChanging(value);
					this.SendPropertyChanging();
					this._BookOver = value;
					this.SendPropertyChanged("BookOver");
					this.OnBookOverChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OldInvoiceCode", DbType="VarChar(20)")]
		public string OldInvoiceCode
		{
			get
			{
				return this._OldInvoiceCode;
			}
			set
			{
				if ((this._OldInvoiceCode != value))
				{
					this.OnOldInvoiceCodeChanging(value);
					this.SendPropertyChanging();
					this._OldInvoiceCode = value;
					this.SendPropertyChanged("OldInvoiceCode");
					this.OnOldInvoiceCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PosYn", DbType="TinyInt")]
		public System.Nullable<byte> PosYn
		{
			get
			{
				return this._PosYn;
			}
			set
			{
				if ((this._PosYn != value))
				{
					this.OnPosYnChanging(value);
					this.SendPropertyChanging();
					this._PosYn = value;
					this.SendPropertyChanged("PosYn");
					this.OnPosYnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PosMoney", DbType="Money")]
		public System.Nullable<decimal> PosMoney
		{
			get
			{
				return this._PosMoney;
			}
			set
			{
				if ((this._PosMoney != value))
				{
					this.OnPosMoneyChanging(value);
					this.SendPropertyChanging();
					this._PosMoney = value;
					this.SendPropertyChanged("PosMoney");
					this.OnPosMoneyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CardType", DbType="Int")]
		public System.Nullable<int> CardType
		{
			get
			{
				return this._CardType;
			}
			set
			{
				if ((this._CardType != value))
				{
					this.OnCardTypeChanging(value);
					this.SendPropertyChanging();
					this._CardType = value;
					this.SendPropertyChanged("CardType");
					this.OnCardTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdvanceYn", DbType="TinyInt")]
		public System.Nullable<byte> AdvanceYn
		{
			get
			{
				return this._AdvanceYn;
			}
			set
			{
				if ((this._AdvanceYn != value))
				{
					this.OnAdvanceYnChanging(value);
					this.SendPropertyChanging();
					this._AdvanceYn = value;
					this.SendPropertyChanged("AdvanceYn");
					this.OnAdvanceYnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoneyType", DbType="Int")]
		public System.Nullable<int> MoneyType
		{
			get
			{
				return this._MoneyType;
			}
			set
			{
				if ((this._MoneyType != value))
				{
					this.OnMoneyTypeChanging(value);
					this.SendPropertyChanging();
					this._MoneyType = value;
					this.SendPropertyChanged("MoneyType");
					this.OnMoneyTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BalanceDt", DbType="VarChar(20)")]
		public string BalanceDt
		{
			get
			{
				return this._BalanceDt;
			}
			set
			{
				if ((this._BalanceDt != value))
				{
					this.OnBalanceDtChanging(value);
					this.SendPropertyChanging();
					this._BalanceDt = value;
					this.SendPropertyChanged("BalanceDt");
					this.OnBalanceDtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdvanceReturn", DbType="TinyInt NOT NULL")]
		public byte AdvanceReturn
		{
			get
			{
				return this._AdvanceReturn;
			}
			set
			{
				if ((this._AdvanceReturn != value))
				{
					this.OnAdvanceReturnChanging(value);
					this.SendPropertyChanging();
					this._AdvanceReturn = value;
					this.SendPropertyChanged("AdvanceReturn");
					this.OnAdvanceReturnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDT", DbType="DateTime NOT NULL")]
		public System.DateTime CreateDT
		{
			get
			{
				return this._CreateDT;
			}
			set
			{
				if ((this._CreateDT != value))
				{
					this.OnCreateDTChanging(value);
					this.SendPropertyChanging();
					this._CreateDT = value;
					this.SendPropertyChanged("CreateDT");
					this.OnCreateDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReviseDT", DbType="DateTime NOT NULL")]
		public System.DateTime ReviseDT
		{
			get
			{
				return this._ReviseDT;
			}
			set
			{
				if ((this._ReviseDT != value))
				{
					this.OnReviseDTChanging(value);
					this.SendPropertyChanging();
					this._ReviseDT = value;
					this.SendPropertyChanged("ReviseDT");
					this.OnReviseDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Creator", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Creator
		{
			get
			{
				return this._Creator;
			}
			set
			{
				if ((this._Creator != value))
				{
					this.OnCreatorChanging(value);
					this.SendPropertyChanging();
					this._Creator = value;
					this.SendPropertyChanged("Creator");
					this.OnCreatorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Operator", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Operator
		{
			get
			{
				return this._Operator;
			}
			set
			{
				if ((this._Operator != value))
				{
					this.OnOperatorChanging(value);
					this.SendPropertyChanging();
					this._Operator = value;
					this.SendPropertyChanged("Operator");
					this.OnOperatorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Old定价", DbType="VarChar(10)")]
		public string Old定价
		{
			get
			{
				return this._Old定价;
			}
			set
			{
				if ((this._Old定价 != value))
				{
					this.OnOld定价Changing(value);
					this.SendPropertyChanging();
					this._Old定价 = value;
					this.SendPropertyChanged("Old定价");
					this.OnOld定价Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Old年月", DbType="VarChar(10)")]
		public string Old年月
		{
			get
			{
				return this._Old年月;
			}
			set
			{
				if ((this._Old年月 != value))
				{
					this.OnOld年月Changing(value);
					this.SendPropertyChanging();
					this._Old年月 = value;
					this.SendPropertyChanged("Old年月");
					this.OnOld年月Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Old客户", DbType="VarChar(10)")]
		public string Old客户
		{
			get
			{
				return this._Old客户;
			}
			set
			{
				if ((this._Old客户 != value))
				{
					this.OnOld客户Changing(value);
					this.SendPropertyChanging();
					this._Old客户 = value;
					this.SendPropertyChanged("Old客户");
					this.OnOld客户Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Old水表", DbType="VarChar(10)")]
		public string Old水表
		{
			get
			{
				return this._Old水表;
			}
			set
			{
				if ((this._Old水表 != value))
				{
					this.OnOld水表Changing(value);
					this.SendPropertyChanging();
					this._Old水表 = value;
					this.SendPropertyChanged("Old水表");
					this.OnOld水表Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Old支付方式", DbType="VarChar(10)")]
		public string Old支付方式
		{
			get
			{
				return this._Old支付方式;
			}
			set
			{
				if ((this._Old支付方式 != value))
				{
					this.OnOld支付方式Changing(value);
					this.SendPropertyChanging();
					this._Old支付方式 = value;
					this.SendPropertyChanged("Old支付方式");
					this.OnOld支付方式Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OldUser", DbType="VarChar(10)")]
		public string OldUser
		{
			get
			{
				return this._OldUser;
			}
			set
			{
				if ((this._OldUser != value))
				{
					this.OnOldUserChanging(value);
					this.SendPropertyChanging();
					this._OldUser = value;
					this.SendPropertyChanged("OldUser");
					this.OnOldUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_otherOrderCode", DbType="VarChar(50)")]
		public string otherOrderCode
		{
			get
			{
				return this._otherOrderCode;
			}
			set
			{
				if ((this._otherOrderCode != value))
				{
					this.OnotherOrderCodeChanging(value);
					this.SendPropertyChanging();
					this._otherOrderCode = value;
					this.SendPropertyChanged("otherOrderCode");
					this.OnotherOrderCodeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
