#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppTest
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="FFSLJ")]
	public partial class aaaDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertBCS_District(BCS_District instance);
    partial void UpdateBCS_District(BCS_District instance);
    partial void DeleteBCS_District(BCS_District instance);
    #endregion
		
		public aaaDataContext() : 
				base(global::IEnumerable.Properties.Settings.Default.FFSLJConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public aaaDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public aaaDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public aaaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public aaaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<BCS_District> BCS_District
		{
			get
			{
				return this.GetTable<BCS_District>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BCS_District")]
	public partial class BCS_District : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Dis_ID;
		
		private string _DepartmentCode;
		
		private string _Code;
		
		private string _DistrictName;
		
		private System.Nullable<int> _MeterReadingRouteID;
		
		private System.Data.Linq.Binary @__MASK_SYNC_V2;
		
		private string _MeterReader;
		
		private System.DateTime _CreateDT;
		
		private System.DateTime _ReviseDT;
		
		private string _Operator;
		
		private string _Creator;
		
		private string _OldCode;
		
		private System.Nullable<int> _AllowOnlinePay;
		
		private string _CollCollector;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDis_IDChanging(long value);
    partial void OnDis_IDChanged();
    partial void OnDepartmentCodeChanging(string value);
    partial void OnDepartmentCodeChanged();
    partial void OnCodeChanging(string value);
    partial void OnCodeChanged();
    partial void OnDistrictNameChanging(string value);
    partial void OnDistrictNameChanged();
    partial void OnMeterReadingRouteIDChanging(System.Nullable<int> value);
    partial void OnMeterReadingRouteIDChanged();
    partial void On_MASK_SYNC_V2Changing(System.Data.Linq.Binary value);
    partial void On_MASK_SYNC_V2Changed();
    partial void OnMeterReaderChanging(string value);
    partial void OnMeterReaderChanged();
    partial void OnCreateDTChanging(System.DateTime value);
    partial void OnCreateDTChanged();
    partial void OnReviseDTChanging(System.DateTime value);
    partial void OnReviseDTChanged();
    partial void OnOperatorChanging(string value);
    partial void OnOperatorChanged();
    partial void OnCreatorChanging(string value);
    partial void OnCreatorChanged();
    partial void OnOldCodeChanging(string value);
    partial void OnOldCodeChanged();
    partial void OnAllowOnlinePayChanging(System.Nullable<int> value);
    partial void OnAllowOnlinePayChanged();
    partial void OnCollCollectorChanging(string value);
    partial void OnCollCollectorChanged();
    #endregion
		
		public BCS_District()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dis_ID", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public long Dis_ID
		{
			get
			{
				return this._Dis_ID;
			}
			set
			{
				if ((this._Dis_ID != value))
				{
					this.OnDis_IDChanging(value);
					this.SendPropertyChanging();
					this._Dis_ID = value;
					this.SendPropertyChanged("Dis_ID");
					this.OnDis_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DepartmentCode", DbType="VarChar(50) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string DepartmentCode
		{
			get
			{
				return this._DepartmentCode;
			}
			set
			{
				if ((this._DepartmentCode != value))
				{
					this.OnDepartmentCodeChanging(value);
					this.SendPropertyChanging();
					this._DepartmentCode = value;
					this.SendPropertyChanged("DepartmentCode");
					this.OnDepartmentCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="VarChar(6) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this.OnCodeChanging(value);
					this.SendPropertyChanging();
					this._Code = value;
					this.SendPropertyChanged("Code");
					this.OnCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DistrictName", DbType="VarChar(40) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string DistrictName
		{
			get
			{
				return this._DistrictName;
			}
			set
			{
				if ((this._DistrictName != value))
				{
					this.OnDistrictNameChanging(value);
					this.SendPropertyChanging();
					this._DistrictName = value;
					this.SendPropertyChanged("DistrictName");
					this.OnDistrictNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MeterReadingRouteID", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> MeterReadingRouteID
		{
			get
			{
				return this._MeterReadingRouteID;
			}
			set
			{
				if ((this._MeterReadingRouteID != value))
				{
					this.OnMeterReadingRouteIDChanging(value);
					this.SendPropertyChanging();
					this._MeterReadingRouteID = value;
					this.SendPropertyChanged("MeterReadingRouteID");
					this.OnMeterReadingRouteIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_MASK_SYNC_V2]", Storage="__MASK_SYNC_V2", AutoSync=AutoSync.Always, DbType="rowversion", IsDbGenerated=true, IsVersion=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary _MASK_SYNC_V2
		{
			get
			{
				return this.@__MASK_SYNC_V2;
			}
			set
			{
				if ((this.@__MASK_SYNC_V2 != value))
				{
					this.On_MASK_SYNC_V2Changing(value);
					this.SendPropertyChanging();
					this.@__MASK_SYNC_V2 = value;
					this.SendPropertyChanged("_MASK_SYNC_V2");
					this.On_MASK_SYNC_V2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MeterReader", DbType="VarChar(16)", UpdateCheck=UpdateCheck.Never)]
		public string MeterReader
		{
			get
			{
				return this._MeterReader;
			}
			set
			{
				if ((this._MeterReader != value))
				{
					this.OnMeterReaderChanging(value);
					this.SendPropertyChanging();
					this._MeterReader = value;
					this.SendPropertyChanged("MeterReader");
					this.OnMeterReaderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDT", DbType="DateTime NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.DateTime CreateDT
		{
			get
			{
				return this._CreateDT;
			}
			set
			{
				if ((this._CreateDT != value))
				{
					this.OnCreateDTChanging(value);
					this.SendPropertyChanging();
					this._CreateDT = value;
					this.SendPropertyChanged("CreateDT");
					this.OnCreateDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReviseDT", DbType="DateTime NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.DateTime ReviseDT
		{
			get
			{
				return this._ReviseDT;
			}
			set
			{
				if ((this._ReviseDT != value))
				{
					this.OnReviseDTChanging(value);
					this.SendPropertyChanging();
					this._ReviseDT = value;
					this.SendPropertyChanged("ReviseDT");
					this.OnReviseDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Operator", DbType="VarChar(16) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Operator
		{
			get
			{
				return this._Operator;
			}
			set
			{
				if ((this._Operator != value))
				{
					this.OnOperatorChanging(value);
					this.SendPropertyChanging();
					this._Operator = value;
					this.SendPropertyChanged("Operator");
					this.OnOperatorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Creator", DbType="VarChar(16) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Creator
		{
			get
			{
				return this._Creator;
			}
			set
			{
				if ((this._Creator != value))
				{
					this.OnCreatorChanging(value);
					this.SendPropertyChanging();
					this._Creator = value;
					this.SendPropertyChanged("Creator");
					this.OnCreatorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OldCode", DbType="VarChar(10)", UpdateCheck=UpdateCheck.Never)]
		public string OldCode
		{
			get
			{
				return this._OldCode;
			}
			set
			{
				if ((this._OldCode != value))
				{
					this.OnOldCodeChanging(value);
					this.SendPropertyChanging();
					this._OldCode = value;
					this.SendPropertyChanged("OldCode");
					this.OnOldCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AllowOnlinePay", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> AllowOnlinePay
		{
			get
			{
				return this._AllowOnlinePay;
			}
			set
			{
				if ((this._AllowOnlinePay != value))
				{
					this.OnAllowOnlinePayChanging(value);
					this.SendPropertyChanging();
					this._AllowOnlinePay = value;
					this.SendPropertyChanged("AllowOnlinePay");
					this.OnAllowOnlinePayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CollCollector", DbType="NVarChar(200)", UpdateCheck=UpdateCheck.Never)]
		public string CollCollector
		{
			get
			{
				return this._CollCollector;
			}
			set
			{
				if ((this._CollCollector != value))
				{
					this.OnCollCollectorChanging(value);
					this.SendPropertyChanging();
					this._CollCollector = value;
					this.SendPropertyChanged("CollCollector");
					this.OnCollCollectorChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
